task:
  name: GolangCI Lint Linux New
  container:
    image: golangci/golangci-lint:latest
  generate_script: go generate ./...
  run_script: golangci-lint run --no-config --enable-all --skip-files "file.go" --skip-files "nss.go" --disable gochecknoglobals,gomnd $GOLANGCI_ARGS -v --out-format json > lint-report.json
  env:
    GOLANGCI_ARGS: "--new-from-rev=HEAD~"
  always:
    golangci_artifacts:
      path: lint-report.json
      type: text/json
      format: golangci
