task:
  container:
    image: golangci/golangci-lint:latest
  generate_script: go generate ./...
  run_script: golangci-lint run --no-config --enable-all --skip-files "file.go" --skip-files "nss.go" --disable gochecknoglobals,gomnd $GOLANGCI_ARGS -v --out-format json > lint-report.json
  matrix:
    - name: Go Lint $GOOS New
      env:
        GOLANGCI_ARGS: "--new-from-rev=HEAD~"
    - name: Go Lint $GOOS Mandatory
      env:
        GOLANGCI_ARGS: "--disable=errorlint,exhaustive,exhaustivestruct,gci,godot,gofumpt,nlreturn,paralleltest"
    - name: Go Lint $GOOS
      env:
        GOLANGCI_ARGS: ""
      allow_failures: true
  matrix:
    - env:
        GOOS: linux
    - env:
        GOOS: windows
  always:
    golangci_artifacts:
      path: lint-report.json
      type: text/json
      format: golangci

task:
  name: ShellCheck
  container:
    image: fedora:latest
  install_script: dnf install -y ShellCheck
  run_script: bash testdata/shellcheck.bash

# TODO: Go Unit tests

# TODO: "Testing config parsing" from travis.bash

# TODO: PowerShell tests

# TODO: Gox builds, multiple Go versions

# TODO: Upload Nightlies

# TODO: IRC notifications on failure

# TODO: Cron
