language: go
go:
  - 1.7.1

addons:
  apt:
    packages:
      - libcap-dev
      - gcc-multilib
      - libc6-dev:i386
      - libcap-dev:i386

sudo: false

install:
  - go get -v -t ./...
script:
  - source ./.travis/script
after_success:
  - source ./.travis/after_success

env:
  # GITHUB_TOKEN for automatic releases
  - secure: "at1oJs7ib7glx3W+zk+OkT041LdknVXirIhN403CIihVUrlOhODY7yCTgvF4Rk0jYBJiT35Q2qxpgfWF2qGnsNsQmjG3ydDWQDCepDc/CgXfLyoiSTJK5vTK72dYWTVsBTycXbj1CbSy2X2ah/KWjc4RcgZ67ER7mDpRU5nFeow="
